language: ruby

sudo: false

services:
  - mysql
  - elasticsearch
  - redis-server

before_install:
  - wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elk.list
  - sudo apt-get remove --purge elasticsearch -y
  - sudo apt-get update && sudo apt-get install elasticsearch -y
  - sudo -i service elasticsearch restart
  #- curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.2-amd64.deb
  #- sudo dpkg -i --force-confnew elasticsearch-7.4.2-amd64.deb
  #- sudo service elasticsearch restart

before_script:
  - bundle exec rake db:schema:load
  - bundle exec rake environment elasticsearch:import:all FORCE=true
  - sleep 10 # Starting ES takes time: https://docs.travis-ci.com/user/database-setup/#elasticsearch

script:
  - bundle exec rspec

notifications:
  email:
    recipients:
      - aurelien@phonoid.com
      - michael.hoste@gmail.com
