language: ruby

sudo: false

services:
  - mysql
  - elasticsearch
  - redis-server

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.2-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.4.2-amd64.deb && sudo service elasticsearch restart

before_script:
  - sleep 10 # Starting ES takes time: https://docs.travis-ci.com/user/database-setup/#elasticsearch

script:
  - bundle exec rspec

notifications:
  email:
    recipients:
      - aurelien@phonoid.com
      - michael.hoste@gmail.com
