dist: bionic # for newest node version

language: ruby

sudo: false

env:
  global:
    - ONCI=true
    - ELASTIC_SEARCH_URL="http://127.0.0.1:9200" # ES is on port 9200 on Travis and 9201 on local

addons: # get google-chrome-stable
  chrome: stable

services:
  - mysql
  - elasticsearch
  - redis-server

before_install:
  - wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elk.list
  - sudo apt-get remove --purge elasticsearch -y
  - sudo apt-get update && sudo apt-get install elasticsearch -y
  - sudo -i service elasticsearch restart

before_script:
  - yarn
  - bundle exec rake db:drop || true
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - sleep 5 # Starting ES takes time: https://docs.travis-ci.com/user/database-setup/#elasticsearch
  - bundle exec rake environment elasticsearch:import:all FORCE=true

script:
  - bundle exec rspec

notifications:
  email:
    recipients:
      - aurelien@phonoid.com
      - michael.hoste@gmail.com
