development:
  adapter: redis
  url: redis://localhost:6379/0
  channel_prefix: sitcom_development_cable

test:
  adapter: test

production:
  adapter: redis
  url: redis://localhost:6379/0

cetic:
  adapter: redis
  url: redis://localhost:6379/0
